server:
      port: 8085

spring:
      application:
                 name: gateway-service-demo

      cloud:
           gateway:  
                   routes:                        
                        - id: Demo-Service
                          uri: lb://DEMO-GATEWAY-APP
                          predicates:
                             - Path=/app/**


                   
                   discovery:
                            locator:
                                   enabled: true
                                   
eureka:
      client:
            serviceURL:
                      defaultZone: http://localhost:8761/eureka
                      
management:
          endpoint:
                  gateway:
                         enabled: true                         
          endpoints:
               web:
                  exposure:
                          include: gateway
                  